import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Head from "next/head";
import Link from "next/link";

const montserrat = localFont({
  src: [
    {
      // path: './fonts/static/Montserrat-Regular.ttf',
      path:'./fonts/Montserrat-VariableFont_wght.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      // path: './fonts/static/Montserrat-Bold.ttf',
      path:'./fonts/Montserrat-Italic-VariableFont_wght.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-montserrat',
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Weather App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&display=swap"
        />
      </head>
      
      <body className={`${montserrat.variable}`}>
        {children}
      </body>
    </html>
  );
}
